/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayPauseInfiniteSliderIndexRouteImport } from './routes/play-pause-infinite-slider/index'
import { Route as ListTransformIndexRouteImport } from './routes/list-transform/index'
import { Route as InkIndexRouteImport } from './routes/ink/index'
import { Route as GlassmorphismIndexRouteImport } from './routes/glassmorphism/index'
import { Route as R3dSliderIndexRouteImport } from './routes/3d-slider/index'
import { Route as R3dRotationIndexRouteImport } from './routes/3d-rotation/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPauseInfiniteSliderIndexRoute =
  PlayPauseInfiniteSliderIndexRouteImport.update({
    id: '/play-pause-infinite-slider/',
    path: '/play-pause-infinite-slider/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ListTransformIndexRoute = ListTransformIndexRouteImport.update({
  id: '/list-transform/',
  path: '/list-transform/',
  getParentRoute: () => rootRouteImport,
} as any)
const InkIndexRoute = InkIndexRouteImport.update({
  id: '/ink/',
  path: '/ink/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassmorphismIndexRoute = GlassmorphismIndexRouteImport.update({
  id: '/glassmorphism/',
  path: '/glassmorphism/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dSliderIndexRoute = R3dSliderIndexRouteImport.update({
  id: '/3d-slider/',
  path: '/3d-slider/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dRotationIndexRoute = R3dRotationIndexRouteImport.update({
  id: '/3d-rotation/',
  path: '/3d-rotation/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-rotation': typeof R3dRotationIndexRoute
  '/3d-slider': typeof R3dSliderIndexRoute
  '/glassmorphism': typeof GlassmorphismIndexRoute
  '/ink': typeof InkIndexRoute
  '/list-transform': typeof ListTransformIndexRoute
  '/play-pause-infinite-slider': typeof PlayPauseInfiniteSliderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-rotation': typeof R3dRotationIndexRoute
  '/3d-slider': typeof R3dSliderIndexRoute
  '/glassmorphism': typeof GlassmorphismIndexRoute
  '/ink': typeof InkIndexRoute
  '/list-transform': typeof ListTransformIndexRoute
  '/play-pause-infinite-slider': typeof PlayPauseInfiniteSliderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-rotation/': typeof R3dRotationIndexRoute
  '/3d-slider/': typeof R3dSliderIndexRoute
  '/glassmorphism/': typeof GlassmorphismIndexRoute
  '/ink/': typeof InkIndexRoute
  '/list-transform/': typeof ListTransformIndexRoute
  '/play-pause-infinite-slider/': typeof PlayPauseInfiniteSliderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-rotation'
    | '/3d-slider'
    | '/glassmorphism'
    | '/ink'
    | '/list-transform'
    | '/play-pause-infinite-slider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-rotation'
    | '/3d-slider'
    | '/glassmorphism'
    | '/ink'
    | '/list-transform'
    | '/play-pause-infinite-slider'
  id:
    | '__root__'
    | '/'
    | '/3d-rotation/'
    | '/3d-slider/'
    | '/glassmorphism/'
    | '/ink/'
    | '/list-transform/'
    | '/play-pause-infinite-slider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dRotationIndexRoute: typeof R3dRotationIndexRoute
  R3dSliderIndexRoute: typeof R3dSliderIndexRoute
  GlassmorphismIndexRoute: typeof GlassmorphismIndexRoute
  InkIndexRoute: typeof InkIndexRoute
  ListTransformIndexRoute: typeof ListTransformIndexRoute
  PlayPauseInfiniteSliderIndexRoute: typeof PlayPauseInfiniteSliderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-pause-infinite-slider/': {
      id: '/play-pause-infinite-slider/'
      path: '/play-pause-infinite-slider'
      fullPath: '/play-pause-infinite-slider'
      preLoaderRoute: typeof PlayPauseInfiniteSliderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-transform/': {
      id: '/list-transform/'
      path: '/list-transform'
      fullPath: '/list-transform'
      preLoaderRoute: typeof ListTransformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ink/': {
      id: '/ink/'
      path: '/ink'
      fullPath: '/ink'
      preLoaderRoute: typeof InkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glassmorphism/': {
      id: '/glassmorphism/'
      path: '/glassmorphism'
      fullPath: '/glassmorphism'
      preLoaderRoute: typeof GlassmorphismIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-slider/': {
      id: '/3d-slider/'
      path: '/3d-slider'
      fullPath: '/3d-slider'
      preLoaderRoute: typeof R3dSliderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-rotation/': {
      id: '/3d-rotation/'
      path: '/3d-rotation'
      fullPath: '/3d-rotation'
      preLoaderRoute: typeof R3dRotationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dRotationIndexRoute: R3dRotationIndexRoute,
  R3dSliderIndexRoute: R3dSliderIndexRoute,
  GlassmorphismIndexRoute: GlassmorphismIndexRoute,
  InkIndexRoute: InkIndexRoute,
  ListTransformIndexRoute: ListTransformIndexRoute,
  PlayPauseInfiniteSliderIndexRoute: PlayPauseInfiniteSliderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
